### ISSUE TITLE
Security Warning when I open project in Visual Studio Community 2017

### ISSUE THREAD

**Issue by alexAlchemy** [MV10/Azure.Functions.Dependency.Injection#1]
![image](https://user-images.githubusercontent.com/32409073/36585177-ba651bda-1874-11e8-9850-dbeac39384f2.png)

I get this warning when I open it saying that the build process is effected. Can you expand on why that is?

Thanks

**Comment by MV10** [comment]
I'm guessing you downloaded it as a ZIP?

Pretty sure that just means Windows tagged it as coming from the Internet. Same as the warnings you get if you download a Word or Excel file. There is a checkbox on the ZIP file properties you could disable. "Unblock" I think, I don't remember exactly what it says, I disable that faux-security on my machines.

**Comment by alexAlchemy** [comment]
Yeah thats correct. Thanks for your speedy response and for your fine work on this project.

Can't believe Azure haven't sorted DI yet!

**Comment by MV10** [comment]
One caveat I really should document -- the function-name attribute is global to your csproj. I didn't realize that until later. That means if you rely on the default "RegisterServices" trigger, you should only have one for the entire csproj.

This actually ends up working pretty well since Functions at the project-level should still be tightly focused and the handful of triggers you create will probably share all or most of the same services.
